AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 100

Metrics/ClassLength:
  Max: 300

Naming/MethodParameterName:
  Enabled: false

Metrics/ParameterLists:
  Max: 10

Metrics/AbcSize:
  Enabled: false
