name: Test/Lint/Release

permissions:
  contents: write

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test-lint:
    if: ${{ !startsWith(github.event.head_commit.message, 'tag') }}
    runs-on: ubuntu-latest
    services:
      signway:
        image: gabotechs/signway
        ports:
          - 3000:3000
        options: my-id my-secret

    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.10
        bundler-cache: true
    - run: bundle exec rake

  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - unit-test-lint
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0' # https://github.com/actions/checkout/issues/217

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.10
          bundler-cache: true

      - name: Tag
        id: tag
        run: |
          version=$(.github/semver.sh)
          git config user.name github-actions
          git config user.email github-actions@github.com
          bundle config set frozen false
          bundle exec bump set $version
          git add Gemfile.lock lib/signway_sdk/version.rb
          git commit -m "tag: v$version"
          git tag "v$version"
          git push
          git push --tags
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Release
        run: gh release create "v${{ steps.tag.outputs.version }}"
        env:
          GH_TOKEN: ${{ github.token }}

      - run: gem build signway_sdk.gemspec
      - run: |
          echo "---\n:rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}\n" >> ~/.gem/credentials
          gem push signway_sdk-${{ steps.tag.outputs.version }}.gem
